// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminConfig = "admin_config"

// AdminConfig mapped from table <admin_config>
type AdminConfig struct {
	ID        int32     `gorm:"column:id;primaryKey;default:1" json:"id"`
	Config    string    `gorm:"column:config;not null" json:"config"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName AdminConfig's table name
func (*AdminConfig) TableName() string {
	return TableNameAdminConfig
}
