// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFavorite = "favorites"

// Favorite mapped from table <favorites>
type Favorite struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username      string    `gorm:"column:username;not null" json:"username"`
	Key           string    `gorm:"column:key;not null" json:"key"`
	Title         string    `gorm:"column:title;not null" json:"title"`
	SourceName    string    `gorm:"column:source_name;not null" json:"source_name"`
	Cover         string    `gorm:"column:cover;not null" json:"cover"`
	Year          string    `gorm:"column:year;not null" json:"year"`
	TotalEpisodes int32     `gorm:"column:total_episodes;not null" json:"total_episodes"`
	SaveTime      time.Time `gorm:"column:save_time;not null;default:CURRENT_TIMESTAMP" json:"save_time"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
