// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlayRecord = "play_records"

// PlayRecord mapped from table <play_records>
type PlayRecord struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username      string    `gorm:"column:username;not null" json:"username"`
	Key           string    `gorm:"column:key;not null" json:"key"`
	Title         string    `gorm:"column:title;not null" json:"title"`
	SourceName    string    `gorm:"column:source_name;not null" json:"source_name"`
	Cover         string    `gorm:"column:cover;not null" json:"cover"`
	Year          string    `gorm:"column:year;not null" json:"year"`
	IndexEpisode  int32     `gorm:"column:index_episode;not null" json:"index_episode"`
	TotalEpisodes int32     `gorm:"column:total_episodes;not null" json:"total_episodes"`
	PlayTime      int32     `gorm:"column:play_time;not null" json:"play_time"`
	TotalTime     int32     `gorm:"column:total_time;not null" json:"total_time"`
	SaveTime      time.Time `gorm:"column:save_time;not null;default:CURRENT_TIMESTAMP" json:"save_time"`
	SearchTitle   string    `gorm:"column:search_title" json:"search_title"`
}

// TableName PlayRecord's table name
func (*PlayRecord) TableName() string {
	return TableNamePlayRecord
}
