// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSearchHistory = "search_history"

// SearchHistory mapped from table <search_history>
type SearchHistory struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string    `gorm:"column:username;not null" json:"username"`
	Keyword   string    `gorm:"column:keyword;not null" json:"keyword"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName SearchHistory's table name
func (*SearchHistory) TableName() string {
	return TableNameSearchHistory
}
